title = input("Enter the webpage title:")
h1 = input("Enter the header:")
h2 = input("Enter the sub header:")
p1 = input("Enter the paragraph1:")
p2 = input("Enter the paragraph2:")
print("<html>")
print("<head>")
print("<title>")
print(title)
print("</title>")
print("</head>")
print("<body>")
print("<h1>")
print(h1)
print("</h1>")
print("<h2>")
print(h2)
print("</h2>")
print("<p1>")
print(p1)
print("</p1>")
print("<p2>")
print(p2)
print("</p2>")
print("</body>")
print("</html>")     



